package com.leandronazareth.mensagens_rabbitmq.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Sms {
    /**
     * Correlation id for the message. Generated by the sender and used by the
     * consumer to correlate a response back to the original request.
     */
    private String id;

    /**
     * The text content of the SMS, or the response text returned by the user/provider.
     */
    private String mensagem;

}
